build:
  image: azuresdk/ci-autorest
  commands:
    - apt-get update -qq
    - apt-get -y install python-pip
    # Install ruby dependencies
    - bash -c "source /usr/local/rvm/scripts/rvm \
      && rvm use 2.3.0 --install --binary --fuzzy
      && gem install bundler"
    - bash -c "source /usr/local/rvm/scripts/rvm \
      && bundle install"
    - pip install --user tox
    # Install android SDK
    - mkdir android
    - wget -qO- "http://dl.google.com/android/android-sdk_r23.0.2-linux.tgz" | tar -zxv -C ./android
    - echo y | ./android/android-sdk-linux/tools/android update sdk --all --filter platform-tools,android-23,build-tools-23.0.1,extra-android-support,extra-android-m2repository,extra-google-m2repository --no-ui --force
    - export ANDROID_HOME=`pwd`/android/android-sdk-linux
    - bash -c "source $DNX_USER_HOME/dnvm/dnvm.sh \
      && dnvm install $DNX_VERSION -r mono -p"
    - npm install
    - gulp